@echo off
REM Cleanup script for workspace - Windows cmd
REM WARNING: This deletes files/folders listed below. Run only if you want to remove them.

echo Deleting frontend/package-lock.json if present...
nd /s /q "e:\YR 2\OS\OS_PROJ\frontend\package-lock.json" 2>nul
echo Deleting frontend/frontend.log if present...
nd /s /q "e:\YR 2\OS\OS_PROJ\frontend\frontend.log" 2>nul
echo Deleting frontend/README.md if present...
nd /s /q "e:\YR 2\OS\OS_PROJ\frontend\README.md" 2>nul
echo Deleting frontend/public/vite.svg if present...
nd /s /q "e:\YR 2\OS\OS_PROJ\frontend\public\vite.svg" 2>nul
echo Deleting frontend/src/style.css if present...
nd /s /q "e:\YR 2\OS\OS_PROJ\frontend\src\style.css" 2>nul
echo Deleting backend/backend.log if present...
nd /s /q "e:\YR 2\OS\OS_PROJ\backend\backend.log" 2>nul
echo Deleting backend/__pycache__ folder if present...
rmdir /s /q "e:\YR 2\OS\OS_PROJ\backend\__pycache__" 2>nul
echo Deleting top-level package-lock.json if present...
nd /s /q "e:\YR 2\OS\OS_PROJ\package-lock.json" 2>nul
echo Done. Please verify files were removed.
pause